name: DockerImageCI
env:
  REPOZITORY_NAME_ECR: "sample"
  REPOZITORY_URI_ECR: "571190452482.dkr.ecr.eu-central-1.amazonaws.com/sample"
  ECS_REGION: "eu-central-1"

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    - name: List docker process and images 
      run: | 
        docker ps -a 
        docker images 
    - name: Check IP and grep
      run : ifconfig | grep inet
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2
    
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: arn:aws:iam::571190452482.dkr.ecr.eu-central-1.amazonaws.com/sample
        aws-region: ${{ env.ECS_REGION}}
        


    









